name: Update Delegators Count

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours

jobs:
  update-delegators:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Run delegators count script
      run: python delegators_count.py

    - name: Commit and push results if there are changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update README.md with delegators count [skip ci]'
          git push
        else
          echo "No changes to commit"
        fi
