name: Update Delegators Count and Plot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 0,6,12,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib pandas selenium requests webdriver-manager

    #- name: Run aptos_delegate.py
    #  run: python aptos_delegate.py

    - name: Run aptos_validators.py
      run: python aptos_validators.py

    - name: Commit and push results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md delegators_data.csv delegators_plot.png validators.txt
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update delegators count, plot, and validator info'
          git push
        else
          echo "No changes to commit"
        fi
