name: Update Delegators Count and Plot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 0,6,12,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium matplotlib pandas webdriver_manager

    # Run delegation_analysis.py
    - name: Run delegation_analysis.py
      run: python delegation_analysis.py

    # Run drop_analysis.py
    - name: Run drop_analysis.py
      run: python drop_analysis.py

    - name: Commit and push results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md delegators_data.csv delegators_plot.png
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update delegators count, plot, and airdrop estimation'
          git push
        else
          echo "No changes to commit"
        fi
